[project]
name = "git-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pytest>=8.3.5",
]

[dependency-groups]
dev = [
"pytest>=8.3.5",
]